### ISSUE TITLE
Import loader create invalid variable name based off package name

### ISSUE THREAD

**Issue by chrisrink** [webpack-contrib/imports-loader#48] opened 2017-04-10 23:17 UTC
Try importing jquery-migrate into a legacy jquery plugin, and you will get a compile error:

`/node_modules/imports-loader/index.js?jQuery=jquery,this=>window,"jquery-igrate"!...node_modules/vh.jquery.ba-bbq/jquery.ba-bbq.js Unexpected token (4:4)
You may need an appropriate loader to handle this file type.
| var jQuery = require("jquery");
| (function() {
| var "jquery-migrate" = require("\"jquery-migrate\"");
| 
| /*!`

My workaround is to create an alias but it would be nice if the import loader replaced invalid variable name characters with underscores or something.

**Comment by michael-ciniawsky** [comment] 2017-04-10 23:26
> /node_modules/imports-loader/index.js?jQuery=jquery,this=>window,"jquery-igrate"!

 `"jquery-igrate"` => `"jquery-migrate"` ?

Please provide more info about your current setup (`webpack.confg.js` etc)

**Comment by bebraw** [comment] 2017-05-06 07:25
@chrisrink Can you set up a small repository showcasing the issue?

**Comment by chrisrink** [comment] 2017-05-07 17:55
Here is a repo you can reproduce with:

https://github.com/chrisrink/webpack-import-issue

I added a few comments in the webpack.config to highlight the issue.

**Comment by evilebottnawi** [comment] 2017-05-16 19:37
@bebraw seems this error also present in `webpack`, using
```js
new webpack.ProvidePlugin({
    'window.jQuery-test': 'jquery',
})
```
Output:
```js
...
/* WEBPACK VAR INJECTION */(function(__webpack_provided_window_dot_jQuery-test) {/* harmony import */
...
```
and error `Uncaught SyntaxError: Unexpected token -`

**Comment by evilebottnawi** [comment] 2017-05-16 19:40
Honestly, I think it's won't fix. In theory we can use `camelcase` or just remove invalid characters, but it is not good solution.

**Comment by evilebottnawi** [comment] 2017-05-16 20:29
Solution:
1. Won't fix - just add caveat about this in docs.
2. Do it as in `webpack` https://github.com/webpack/webpack/blob/f66439e2b736db381481d42988076f39d30d77a5/lib/dependencies/HarmonyModulesHelpers.js#L16 (but it is can't working with some scripts try to access using `globals['jquery-migrate']`, `this['jquery-migrate']`, `windows['jquery-migrate']`)
3. Add new operator (example `jquery-migrate>jquerymigrate`) to allow using own names.
`jquery-migrate>jquerymigrate` -> `var jquerymigrate = require('jquery-migrate')`
`jquery-migrate>this.jquerymigrate` -> `this.jquerymigrate = require('jquery-migrate')`
`jquery-migrate>variable.jquerymigrate` -> `variable.jquerymigrate = require('jquery-migrate')`

**Comment by bebraw** [comment] 2017-05-17 05:56
Yeah, I can see why this fails. The problem is that if you rewrite the name, you could theoretically end up with a name clash (it maps to an existing name). I think going through a string based lookup is a good way to solve this as it avoids the problem. Having a new operator for this and pushing the problem to the user doesn't feel right (could be done regardless, though).

It would be good to fix `ProvidePlugin` while at it. Maybe the solution could be shared.

**Comment by evilebottnawi** [comment] 2017-05-17 09:42
@bebraw 
>  I think going through a string based lookup is a good way to solve this as it avoids the problem.

Little did not understand, can you give more details?

**Comment by bebraw** [comment] 2017-05-17 09:46
@evilebottnawi `(this['jquery-migrate'])` or some other variant over `(jquery-migrate)` (invalid syntax).

**Comment by evilebottnawi** [comment] 2017-05-17 10:48
@bebraw using `this` is incorrect:
Now:
```js
// Improted
var library = require('library');

// Code in library
function test() {
   library.on('', function() { });
}
```
After your suggestions
```js
// Improted
(this['library'] = require('library'));

// Code in library
function test() {
   library.on('', function() { }); // Ops, not library in this context
}
```

**Comment by evilebottnawi** [comment] 2017-05-17 10:55
For me best solution add new operator, it is allow to see how library using library ('jqueryMigrate', `jquerymigrate`, `this.jquerymigrate`, `window.jquerymigrate`) and setup this right.

**Comment by bebraw** [comment] 2017-05-17 10:57
@evilebottnawi I did not mean it literally. Most likely you need something else than `this` depending on the surrounding code.

**Comment by evilebottnawi** [comment] 2017-05-17 10:58
@bebraw i tried many solution, no found universal :disappointed:

**Comment by bebraw** [comment] 2017-05-17 11:01
@evilebottnawi I guess the way that remains is to find an acceptable `replace` for `-`. This feels like a common enough problem so there's likely some convention somewhere. Maybe `_` and then detect clashes (give warning) to play it safe?

**Comment by evilebottnawi** [comment] 2017-05-17 11:04
@bebraw hm, I was wrong: 
```js
// Improted
(this['library'] = require('library'));

// Code in library
function Test() {
   library.on('', function() {});
}

var test = new Test();
```
It is work as expected, seems it si good solution, I'll try to see where the context might be broken, if nowhere, perhaps, this is a good solution.

**Comment by evilebottnawi** [comment] 2017-05-17 12:08
Solution:
```js
var global = (function(){ return this || (1,eval)('this') })();
global['my-variable'] = require('my-varialbe');
```

**Comment by bebraw** [comment] 2017-05-17 12:21
@evilebottnawi Ok, that `eval` is fairly tricky. Maybe better wait for more feedback on this to see if we can eliminate that.

**Comment by evilebottnawi** [comment] 2017-05-17 12:27
@bebraw I think we are unlikely to get many answers here, a rare use case, in fact, i don't see in my decision what is really bad, yep `eval` is bad, but it is allow get global context in whatever environments.

**Comment by bebraw** [comment] 2017-05-17 12:31
@evilebottnawi Ok, basically it's fine by me as long as the reason is documented well like that.

**Comment by evilebottnawi** [comment] 2017-05-17 12:32
@d3viant0ne what do your this about this?

**Comment by evilebottnawi** [comment] 2017-05-17 13:47
Other solution https://github.com/zloirock/core-js/blob/master/modules/_global.js

**Comment by Kovensky** [comment] 2017-05-17 22:38
This discussion is going in the wrong direction. imports-loader is for injecting values _in this module's scope_, not put things in global just because you can't find a local name.

**Comment by evilebottnawi** [comment] 2017-05-18 09:39
@Kovensky your have another solution for this?

**Comment by evilebottnawi** [comment] 2017-05-18 10:02
@Kovensky many people use `imports-loader` for injecting values :smile: If your know best solution for injecting values in `scripts`, provide this here and let's add this in docs.

**Comment by Kovensky** [comment] 2017-05-18 10:12
`expose-loader`.

**Comment by evilebottnawi** [comment] 2017-05-18 10:17
@Kovensky hm, you're right, i'm ashamed, not familiar with `expose-loader`, because don't use library using the global object :smile: Seems `-` to `_` is good solution (also add docs about this).

**Comment by evilebottnawi** [comment] 2017-05-19 11:22
@bebraw friendly ping

**Comment by bebraw** [comment] 2017-05-20 06:18
> Seems - to _ is good solution (also add docs about this).

That's fine. 👍

**Closed** 2020-06-16 23:51 UTC
Labels: priority: 2 (urgent), type: Bug
